# Site settings
title: Vishal Mishra Blog
email: noemail@example.com
description: > # this means to ignore newlines until "baseurl:"
  THIS IS TEST Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vishal-mishra.github.io/" # the base hostname & protocol for your site
twitter_username: _VishalMishra
github_username:  vishal-mishra

# Build settings
markdown: kramdown
